name: Build & Deploy
on:
  push:
    branches: [master]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            mkdir soerat-kabar-api 
            cd soerat-kabar-api 
            git clone git@github.com:Lykoi-Tech/soerat-kabar-api.git .
            touch .env
            echo HTTP_PORT = ${{ secrets.HTTP_PORT }} >> .env
            echo MONGO_DATABASE_URL = ${{ secrets.MONGO_DATABASE_URL }} >> .env
            echo JWT_SECRET = ${{ secrets.JWT_SECRET }} >> .env
            npm install
            pm2 restart soerat-kabar-api
